services:
  api:
    depends_on:
      postgres:
        condition: service_healthy
    build: ./prf-todos-api
    ports:
      - "5000:5000"
    volumes:
      - ./prf-todos-api:/app

  postgres:
    image: "postgres:15-alpine"
    volumes:
      - prftodos-db-data:/var/lib/pgsql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=prftodos
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 10s
      retries: 5
volumes:
  prftodos-db-data: